# This repository is for use as an upstream source for other repositories.
- self:
    - repo:
        url: https://github.com/common-repo/upstream
        ref: v2.1.2

# Include src/ contents, declare release.yaml as a template, and rename src/ to
# root directory.
- include:
    - "src/**"
- template:
    - "src/.github/workflows/release.yaml"
- rename:
    - "^src/(.*)$": "$1"
- repo:
    url: https://github.com/common-repo/conventional-commits
    ref: v1.3.0
